
- name: Update apt repo and cache on all Ubuntu boxes
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true

- name: Upgrade all packages on servers
  apt: upgrade=dist force_apt_get=yes
  become: true

- name: Install pip
  apt:
    name: python3-pip
    state: present
  become: true

- name: Install kubernetes python module
  pip:
    name: kubernetes
    extra_args: --break-system-packages
    state: present
  become: true