---
# handlers file for ansible_role_microk8s

- name: Refresh certs
  become: yes
  command: microk8s refresh-certs

- name: Restart microk8s
  service:
    name: snap.microk8s.daemon-apiserver
    state: restarted
